# This is a basic workflow to help you get started with Actions

# 文件名称
name: CI

# Controls when the workflow will run
# 何时触发此CI
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '20 23,13 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# 出发后执行的操作 后跟多个键 表示执行哪些操作 注意：这些操作为同时进行
jobs:
  # This workflow contains a single job called "build" 本工作的名称
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: install php
        run: |
          sudo apt-get install php -y
      - name: set config
        run: |
          sudo echo "appid="${{ secrets.appid }} > config.ini
          sudo echo "appsecret="${{ secrets.APPSECRET }} >> config.ini
          sudo echo "key="${{ secrets.KEY }} >> config.ini
          sudo echo "city="${{ secrets.CITY }} >> config.ini
          sudo echo "togetherdays="${{ secrets.TOGETHERDAYS }} >> config.ini
          sudo echo "birthday1="${{ secrets.BIRTHDAY1 }} >> config.ini
          sudo echo "birthday2="${{ secrets.BIRTHDAY2 }} >> config.ini
          sudo echo "touser="${{ secrets.TOUSER }} >> config.ini
          sudo echo "template_id="${{ secrets.TEMPLATE_ID }} >> config.ini
      - name: start post
        run: |
          sudo php wechat.php

